services:
  backend:
    container_name: backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      ENV: ${ENV}
      BACKEND_PORT: ${BACKEND_PORT}
      POSTGRES_URL: ${POSTGRES_URL}

      # Mail
      RESEND_API_KEY: ${RESEND_API_KEY}
      MAIL_DEFAULT_SENDER: ${MAIL_DEFAULT_SENDER}

      # RabbitMQ
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - caddy
      - database
      - rabbitmq

  postgres:
    image: postgres:18.3-alpine
    container_name: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    command: postgres -c 'max_connections=100'
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-h",
          "localhost",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - database

  rabbitmq:
    container_name: rabbitmq
    restart: always
    image: rabbitmq:4.2.5-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./mq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - caddy
      - rabbitmq

  mq-worker:
    container_name: mq-worker
    restart: always
    volumes:
      - ../mq-worker:/app
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      ENV: ${ENV}
      BASE_URL: ${BASE_URL}
      POSTGRES_URL: ${POSTGRES_URL}

      # Mail
      RESEND_API_KEY: ${RESEND_API_KEY}
      MAIL_DEFAULT_SENDER: ${MAIL_DEFAULT_SENDER}

      # RabbitMQ
      RABBITMQ_URL: ${RABBITMQ_URL}
    networks:
      - database
      - rabbitmq

  caddy:
    image: caddy:2.11.2-alpine
    container_name: caddy
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
    networks:
      - caddy

volumes:
  postgres:
  caddy_data:
  caddy_config:
  rabbitmq_data:

networks:
  caddy:
  database:
  rabbitmq:
