services:
  backend:
    build:
      context: ../
      dockerfile: docker/stack/backend/Dockerfile.local
    volumes:
      - ../backend:/app

  postgres:
    ports:
      - 5432:5432

  redis:
    ports:
      - 6379:6379

  worker:
    build:
      context: ../
      dockerfile: docker/stack/worker/Dockerfile.local

  frontend:
    container_name: frontend
    build:
      context: ../
      dockerfile: docker/stack/frontend/Dockerfile.local
    networks:
      - caddy
    volumes:
      - /app/node_modules
      - ../frontend:/app

  caddy:
    volumes:
      - ./caddy/local/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
