services:
  backend:
    build:
      context: ../
      dockerfile: docker/stack/backend/Dockerfile.local
    volumes:
      - ../backend:/app

  mailpit:
    image: axllent/mailpit:v1.29
    container_name: mailpit
    restart: always
    volumes:
      - mailpit:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - mydaily

  postgres:
    ports:
      - 5432:5432

  caddy:
    volumes:
      - ./caddy/local/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  mailpit:
