// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOrUpdateGithubCredentials = `-- name: CreateOrUpdateGithubCredentials :one
INSERT INTO
    github_credentials (
        user_id,
        github_id,
        github_username,
        github_name,
        github_email,
        github_avatar_url,
        github_profile_url,
        access_token,
        token_type,
        scope,
        refresh_token,
        token_expires_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12
    )
ON CONFLICT (user_id) DO
UPDATE
SET
    github_id = EXCLUDED.github_id,
    github_username = EXCLUDED.github_username,
    github_name = EXCLUDED.github_name,
    github_email = EXCLUDED.github_email,
    github_avatar_url = EXCLUDED.github_avatar_url,
    github_profile_url = EXCLUDED.github_profile_url,
    access_token = EXCLUDED.access_token,
    token_type = EXCLUDED.token_type,
    scope = EXCLUDED.scope,
    refresh_token = EXCLUDED.refresh_token,
    token_expires_at = EXCLUDED.token_expires_at,
    updated_at = CURRENT_TIMESTAMP
RETURNING
    id, user_id, github_id, github_username, github_name, github_email, github_avatar_url, github_profile_url, access_token, token_type, scope, refresh_token, token_expires_at, created_at, updated_at
`

type CreateOrUpdateGithubCredentialsParams struct {
	UserID           uuid.UUID      `json:"user_id"`
	GithubID         int64          `json:"github_id"`
	GithubUsername   string         `json:"github_username"`
	GithubName       sql.NullString `json:"github_name"`
	GithubEmail      sql.NullString `json:"github_email"`
	GithubAvatarUrl  sql.NullString `json:"github_avatar_url"`
	GithubProfileUrl sql.NullString `json:"github_profile_url"`
	AccessToken      string         `json:"access_token"`
	TokenType        string         `json:"token_type"`
	Scope            sql.NullString `json:"scope"`
	RefreshToken     sql.NullString `json:"refresh_token"`
	TokenExpiresAt   sql.NullTime   `json:"token_expires_at"`
}

func (q *Queries) CreateOrUpdateGithubCredentials(ctx context.Context, arg CreateOrUpdateGithubCredentialsParams) (GithubCredential, error) {
	row := q.db.QueryRowContext(ctx, createOrUpdateGithubCredentials,
		arg.UserID,
		arg.GithubID,
		arg.GithubUsername,
		arg.GithubName,
		arg.GithubEmail,
		arg.GithubAvatarUrl,
		arg.GithubProfileUrl,
		arg.AccessToken,
		arg.TokenType,
		arg.Scope,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	var i GithubCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GithubID,
		&i.GithubUsername,
		&i.GithubName,
		&i.GithubEmail,
		&i.GithubAvatarUrl,
		&i.GithubProfileUrl,
		&i.AccessToken,
		&i.TokenType,
		&i.Scope,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGithubCredentialsByUserID = `-- name: GetGithubCredentialsByUserID :one
SELECT id, user_id, github_id, github_username, github_name, github_email, github_avatar_url, github_profile_url, access_token, token_type, scope, refresh_token, token_expires_at, created_at, updated_at FROM github_credentials WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetGithubCredentialsByUserID(ctx context.Context, userID uuid.UUID) (GithubCredential, error) {
	row := q.db.QueryRowContext(ctx, getGithubCredentialsByUserID, userID)
	var i GithubCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GithubID,
		&i.GithubUsername,
		&i.GithubName,
		&i.GithubEmail,
		&i.GithubAvatarUrl,
		&i.GithubProfileUrl,
		&i.AccessToken,
		&i.TokenType,
		&i.Scope,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
