// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ModelProvider string

const (
	ModelProviderOpenai ModelProvider = "openai"
	ModelProviderClaude ModelProvider = "claude"
	ModelProviderGemini ModelProvider = "gemini"
	ModelProviderGrok   ModelProvider = "grok"
)

func (e *ModelProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModelProvider(s)
	case string:
		*e = ModelProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for ModelProvider: %T", src)
	}
	return nil
}

type NullModelProvider struct {
	ModelProvider ModelProvider `json:"model_provider"`
	Valid         bool          `json:"valid"` // Valid is true if ModelProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModelProvider) Scan(value interface{}) error {
	if value == nil {
		ns.ModelProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModelProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModelProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModelProvider), nil
}

type ModelKey struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	Provider        ModelProvider  `json:"provider"`
	KeyName         string         `json:"key_name"`
	EncryptedApiKey string         `json:"encrypted_api_key"`
	KeyLast4        sql.NullString `json:"key_last4"`
	IsActive        bool           `json:"is_active"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type User struct {
	ID              uuid.UUID      `json:"id"`
	HashedPassword  sql.NullString `json:"hashed_password"`
	FullName        string         `json:"full_name"`
	Email           string         `json:"email"`
	IsActive        bool           `json:"is_active"`
	IsEmailVerified bool           `json:"is_email_verified"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}
