// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type UserRole string

const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type GithubCredential struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	GithubID         int64          `json:"github_id"`
	GithubUsername   string         `json:"github_username"`
	GithubName       sql.NullString `json:"github_name"`
	GithubEmail      sql.NullString `json:"github_email"`
	GithubAvatarUrl  sql.NullString `json:"github_avatar_url"`
	GithubProfileUrl sql.NullString `json:"github_profile_url"`
	AccessToken      string         `json:"access_token"`
	TokenType        string         `json:"token_type"`
	Scope            sql.NullString `json:"scope"`
	RefreshToken     sql.NullString `json:"refresh_token"`
	TokenExpiresAt   sql.NullTime   `json:"token_expires_at"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type User struct {
	ID              uuid.UUID      `json:"id"`
	HashedPassword  sql.NullString `json:"hashed_password"`
	FullName        string         `json:"full_name"`
	Email           string         `json:"email"`
	IsActive        bool           `json:"is_active"`
	IsEmailVerified bool           `json:"is_email_verified"`
	Role            UserRole       `json:"role"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}
