// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActivateUser(ctx context.Context, arg ActivateUserParams) (User, error)
	CreateOrUpdateGithubCredentials(ctx context.Context, arg CreateOrUpdateGithubCredentialsParams) (GithubCredential, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetGithubCredentialsByUserID(ctx context.Context, userID uuid.UUID) (GithubCredential, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error)
	SoftDeleteUserByEmail(ctx context.Context, email string) error
	SoftDeleteUserByEmailMany(ctx context.Context, email string) error
	SoftDeleteUserById(ctx context.Context, id uuid.UUID) error
	SoftDeleteUserByIdMany(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
