// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const activateUser = `-- name: ActivateUser :one
UPDATE users
SET
    is_active = TRUE,
    hashed_password = $2,
    is_email_verified = TRUE
WHERE
    id = $1
RETURNING
    id, hashed_password, full_name, email, is_active, is_email_verified, created_at, updated_at
`

type ActivateUserParams struct {
	ID             uuid.UUID      `json:"id"`
	HashedPassword sql.NullString `json:"hashed_password"`
}

func (q *Queries) ActivateUser(ctx context.Context, arg ActivateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, activateUser, arg.ID, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (full_name, email)
VALUES ($1, $2)
RETURNING
    id, hashed_password, full_name, email, is_active, is_email_verified, created_at, updated_at
`

type CreateUserParams struct {
	FullName string `json:"full_name"`
	Email    string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.FullName, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, hashed_password, full_name, email, is_active, is_email_verified, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, hashed_password, full_name, email, is_active, is_email_verified, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
WITH
    params AS (
        SELECT
            BTRIM(
                COALESCE($1, '')::text
            ) AS search,
            LOWER(
                BTRIM(
                    COALESCE(
                        $2,
                        'created_at'
                    )::text
                )
            ) AS order_by,
            LOWER(
                BTRIM(
                    COALESCE($3, 'desc')::text
                )
            ) AS order_dir,
            COALESCE($4, 10)::int AS limit_rows,
            COALESCE($5, 1)::int AS offset_rows,
            COALESCE(
                $6,
                false
            )::bool AS exclude_sensitive
    )
SELECT
    u.id,
    CASE
        WHEN p.exclude_sensitive THEN NULL::varchar(255)
        ELSE u.hashed_password
    END AS hashed_password,
    u.full_name,
    u.email,
    u.is_active,
    u.is_email_verified,
    u.created_at,
    u.updated_at
FROM users AS u
    CROSS JOIN params AS p
WHERE
    p.search = ''
    OR u.id::text ILIKE '%' || p.search || '%'
    OR u.full_name ILIKE '%' || p.search || '%'
    OR u.email ILIKE '%' || p.search || '%'
    OR u.is_active::text ILIKE '%' || p.search || '%'
    OR u.is_email_verified::text ILIKE '%' || p.search || '%'
    OR u.created_at::text ILIKE '%' || p.search || '%'
    OR u.updated_at::text ILIKE '%' || p.search || '%'
ORDER BY
    -- ASC ordering by whitelisted fields only.
    CASE
        WHEN p.order_dir = 'asc'
        AND p.order_by = 'id' THEN u.id
    END ASC,
    CASE
        WHEN p.order_dir = 'asc'
        AND p.order_by = 'full_name' THEN u.full_name
    END ASC,
    CASE
        WHEN p.order_dir = 'asc'
        AND p.order_by = 'email' THEN u.email
    END ASC,
    CASE
        WHEN p.order_dir = 'asc'
        AND p.order_by = 'is_active' THEN u.is_active
    END ASC,
    CASE
        WHEN p.order_dir = 'asc'
        AND p.order_by = 'is_email_verified' THEN u.is_email_verified
    END ASC,
    CASE
        WHEN p.order_dir = 'asc'
        AND p.order_by = 'created_at' THEN u.created_at
    END ASC,
    CASE
        WHEN p.order_dir = 'asc'
        AND p.order_by = 'updated_at' THEN u.updated_at
    END ASC,
    -- DESC ordering by whitelisted fields only.
    CASE
        WHEN p.order_dir = 'desc'
        AND p.order_by = 'id' THEN u.id
    END DESC,
    CASE
        WHEN p.order_dir = 'desc'
        AND p.order_by = 'full_name' THEN u.full_name
    END DESC,
    CASE
        WHEN p.order_dir = 'desc'
        AND p.order_by = 'email' THEN u.email
    END DESC,
    CASE
        WHEN p.order_dir = 'desc'
        AND p.order_by = 'is_active' THEN u.is_active
    END DESC,
    CASE
        WHEN p.order_dir = 'desc'
        AND p.order_by = 'is_email_verified' THEN u.is_email_verified
    END DESC,
    CASE
        WHEN p.order_dir = 'desc'
        AND p.order_by = 'created_at' THEN u.created_at
    END DESC,
    CASE
        WHEN p.order_dir = 'desc'
        AND p.order_by = 'updated_at' THEN u.updated_at
    END DESC,
    -- Stable default fallback: latest users first.
    u.created_at DESC
LIMIT CASE
        WHEN p.limit_rows = -1 THEN NULL
        WHEN p.limit_rows < 0 THEN 10
        WHEN p.limit_rows = 0 THEN 10
        ELSE p.limit_rows
    END
OFFSET
    CASE
        WHEN p.offset_rows < 0 THEN 1
        WHEN p.offset_rows = 0 THEN 1
        ELSE p.offset_rows
    END
`

type GetUsersParams struct {
	Search           sql.NullString `json:"search"`
	OrderBy          sql.NullString `json:"order_by"`
	OrderDir         sql.NullString `json:"order_dir"`
	LimitRows        sql.NullInt32  `json:"limit_rows"`
	OffsetRows       sql.NullInt32  `json:"offset_rows"`
	ExcludeSensitive sql.NullBool   `json:"exclude_sensitive"`
}

type GetUsersRow struct {
	ID              uuid.UUID   `json:"id"`
	HashedPassword  interface{} `json:"hashed_password"`
	FullName        string      `json:"full_name"`
	Email           string      `json:"email"`
	IsActive        bool        `json:"is_active"`
	IsEmailVerified bool        `json:"is_email_verified"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsers,
		arg.Search,
		arg.OrderBy,
		arg.OrderDir,
		arg.LimitRows,
		arg.OffsetRows,
		arg.ExcludeSensitive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersRow{}
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.HashedPassword,
			&i.FullName,
			&i.Email,
			&i.IsActive,
			&i.IsEmailVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUserByEmail = `-- name: SoftDeleteUserByEmail :exec
UPDATE users SET is_active = FALSE WHERE email = $1
`

func (q *Queries) SoftDeleteUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, softDeleteUserByEmail, email)
	return err
}

const softDeleteUserByEmailMany = `-- name: SoftDeleteUserByEmailMany :exec
UPDATE users SET is_active = FALSE WHERE email = ANY ($1)
`

func (q *Queries) SoftDeleteUserByEmailMany(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, softDeleteUserByEmailMany, email)
	return err
}

const softDeleteUserById = `-- name: SoftDeleteUserById :exec
UPDATE users SET is_active = FALSE WHERE id = $1
`

func (q *Queries) SoftDeleteUserById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteUserById, id)
	return err
}

const softDeleteUserByIdMany = `-- name: SoftDeleteUserByIdMany :exec
UPDATE users SET is_active = FALSE WHERE id = ANY ($1)
`

func (q *Queries) SoftDeleteUserByIdMany(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteUserByIdMany, id)
	return err
}
