FROM golang:1.26.2-alpine

RUN apk add --no-cache gcc musl-dev
ENV CGO_ENABLED=1
ENV GIN_MODE=debug

# Install tools
RUN go install github.com/air-verse/air@v1.65.1

WORKDIR /app

COPY worker/go.mod worker/go.sum ./
RUN go mod download && go mod verify

COPY worker/ .

CMD ["air", "--build.cmd=go build -o ./tmp/worker ./main.go", "--build.entrypoint=./tmp/worker", "--build.exclude_dir=tmp,test"]
