FROM golang:1.26.2-alpine

RUN apk add --no-cache gcc musl-dev
ENV CGO_ENABLED=1
ENV GIN_MODE=debug

# Install tools
RUN go install github.com/air-verse/air@v1.65.1

WORKDIR /app

COPY mq-worker/go.mod mq-worker/go.sum ./
RUN go mod download && go mod verify

COPY mq-worker/ .

EXPOSE 8080

CMD ["air", "--build.cmd=go build -o ./tmp/mq-worker ./main.go", "--build.entrypoint=./tmp/mq-worker", "--build.exclude_dir=tmp,test"]
